-- v61 資料中心正式版：清掉錯誤爬蟲資料，保留乾淨欄位與前台讀取權限

-- 1) 確保 daily_games 欄位足夠
create table if not exists public.daily_games (
  id uuid default gen_random_uuid() primary key,
  game_date date,
  sport text,
  league text,
  game_time text,
  away text,
  home text,
  money text,
  spread text,
  total text,
  confidence int[] default array[60,60,60],
  source_url text,
  source_name text,
  analysis_json jsonb default '{}'::jsonb,
  active boolean default true,
  updated_at timestamptz default now()
);

alter table public.daily_games enable row level security;
drop policy if exists "daily_games_select_all" on public.daily_games;
create policy "daily_games_select_all"
on public.daily_games
for select
to anon, authenticated
using (true);

grant usage on schema public to anon, authenticated;
grant select on public.daily_games to anon, authenticated;

-- 2) 同步狀態表
create table if not exists public.daily_sync_status (
  id bigint generated by default as identity primary key,
  status text,
  message text,
  games_count int default 0,
  source text default 'github_actions',
  created_at timestamptz default now()
);

alter table public.daily_sync_status enable row level security;
drop policy if exists "daily_sync_status_select_all" on public.daily_sync_status;
create policy "daily_sync_status_select_all"
on public.daily_sync_status
for select
to anon, authenticated
using (true);

grant select on public.daily_sync_status to anon, authenticated;

-- 3) 關閉先前錯誤資料：足球比分/排名被誤塞 MLB、或測試賽事、或隊伍名稱異常
update public.daily_games
set active = false,
    updated_at = now()
where
  away ~* '(^| )([0-9]+)\s*(vs|v\.s\.|VS)|\bS\.\s*[0-9]'
  or home ~* '(^| )([0-9]+)\s*(vs|v\.s\.|VS)|\bS\.\s*[0-9]'
  or away in ('天使','太空人','落磯')
  or home in ('老虎','遊騎兵','道奇')
  or away ilike '%戰資訊%'
  or home ilike '%戰資訊%'
  or away ilike '%賽事資訊%'
  or home ilike '%賽事資訊%';

-- 4) 統一聯盟分類
update public.daily_games set sport='baseball', league='MLB' where league in ('美國職棒','美職','美棒');
update public.daily_games set sport='baseball', league='NPB' where league in ('日本職棒','日職');
update public.daily_games set sport='baseball', league='CPBL' where league in ('中華職棒','台棒');
update public.daily_games set sport='baseball', league='KBO' where league in ('韓國職棒','韓職');
update public.daily_games set sport='basketball', league='WNBA' where league = 'WNBA';
update public.daily_games set sport='basketball', league='NBA' where league = 'NBA';
update public.daily_games set sport='basketball', league='CBA' where league in ('中國職籃','CBA');
update public.daily_games set sport='football', league='足球' where league in ('足球','soccer','football');

-- 5) 查詢目前每日資料狀態
select game_date, sport, league, active, count(*) as games_count, max(updated_at) as last_update
from public.daily_games
group by game_date, sport, league, active
order by game_date desc, sport, league, active desc;
