-- v65 今日/明日賽事正式版
-- 1) 新增 today/tomorrow 與 upcoming/finished 欄位
-- 2) 只讓前台顯示 active=true + game_status='upcoming'
-- 3) 清掉舊版錯誤/測試資料，避免足球比分或測試賽事跑到 MLB

alter table public.daily_games
  add column if not exists game_day_type text default 'today',
  add column if not exists game_status text default 'upcoming';

update public.daily_games
set game_day_type = coalesce(game_day_type, 'today'),
    game_status = coalesce(game_status, 'upcoming');

-- 清掉舊測試賽事與錯誤格式
update public.daily_games
set active = false,
    updated_at = now()
where away in ('天使','太空人','落磯')
   or home in ('老虎','遊騎兵','道奇')
   or away ~* '(^|\s)(vs|v\.s\.?)(\s|$)'
   or home ~* '(^|\s)(vs|v\.s\.?)(\s|$)'
   or away ~* 'S\.\s*\d'
   or home ~* 'S\.\s*\d'
   or away like '%戰資訊%'
   or home like '%戰資訊%';

-- 讓前台可讀 daily_games
grant usage on schema public to anon, authenticated;
grant select on public.daily_games to anon, authenticated;

-- 如果有開 RLS，保留讀取政策
alter table public.daily_games enable row level security;
drop policy if exists "daily_games_select_all" on public.daily_games;
create policy "daily_games_select_all"
on public.daily_games
for select
to anon, authenticated
using (true);

-- 同步狀態表
create table if not exists public.daily_sync_status (
  id bigint generated by default as identity primary key,
  status text,
  message text,
  games_count int default 0,
  source text default 'github_actions',
  created_at timestamptz default now()
);

alter table public.daily_sync_status enable row level security;
drop policy if exists "daily_sync_status_select_all" on public.daily_sync_status;
create policy "daily_sync_status_select_all"
on public.daily_sync_status
for select
to anon, authenticated
using (true);

select game_date, game_day_type, game_status, sport, league, active, count(*) as games_count
from public.daily_games
group by game_date, game_day_type, game_status, sport, league, active
order by game_date desc, game_day_type, sport, league;
